// Generated by delombok at Mon Jul 15 18:44:01 PDT 2019
package com.stripe.exception;

public class CardException extends StripeException {
  private static final long serialVersionUID = 2L;
  private String param;
  private String declineCode;
  private String charge;

  /**
   * Constructs a new card exception with the specified details.
   */
  public CardException(String message, String requestId, String code, String param, String declineCode, String charge, Integer statusCode, Throwable e) {
    super(message, requestId, code, statusCode, e);
    this.param = param;
    this.declineCode = declineCode;
    this.charge = charge;
  }

  @java.lang.SuppressWarnings("all")
  // // @lombok.Generated
  public String getParam() {
    return this.param;
  }

  @java.lang.SuppressWarnings("all")
  // // @lombok.Generated
  public String getDeclineCode() {
    return this.declineCode;
  }

  @java.lang.SuppressWarnings("all")
  // @lombok.Generated
  public String getCharge() {
    return this.charge;
  }
}
