// Generated by delombok at Mon Jul 15 18:44:01 PDT 2019
package com.stripe.exception;

public class SignatureVerificationException extends StripeException {
  private static final long serialVersionUID = 2L;
  private final String sigHeader;

  public SignatureVerificationException(String message, String sigHeader) {
    super(message, null, null, 0);
    this.sigHeader = sigHeader;
  }

  @java.lang.SuppressWarnings("all")
  // @lombok.Generated
  public String getSigHeader() {
    return this.sigHeader;
  }
}
